import { detachIssue } from './detachIssue'
import { DateTime } from 'luxon'
import invariant from 'tiny-invariant'
import fs from 'fs'

const webhookLogger = (event: WebhookEvent) => {
	const file: any = fs.readFileSync('./webhooklog.json', 'utf8')
	const webhookLog = JSON.parse(file)
	webhookLog.push(event)

	fs.writeFileSync('./webhooklog.json', JSON.stringify(webhookLog, null, 2))
	console.info('event logged')
}

const deletedAttachment: CheckCase = ({ action, resource }) =>
	action === 'deleted' && resource.resource_type === 'attachment'

const taskChanged: CheckCase = ({ action, resource }) =>
	action === 'changed' && resource.resource_type === 'task'

const statusChanged: CheckCase = ({ action, resource, parent }) =>
	action === 'added' &&
	resource.resource_type === 'task' &&
	parent?.resource_type === 'section'

const taskAssigned: CheckCase = ({ action, change, parent }) =>
	action === 'changed' &&
	change?.action === 'changed' &&
	change?.field === 'assignee' &&
	parent === null
const tagChanged: CheckCase = ({ parent }) => parent?.resource_type === 'tag'

/**
 * It takes an array of webhook events and then calls a function to handle
 * each event
 * @param events - Array<WebhookEvent>
 */
export const webhookHandler = async (events: Array<WebhookEvent>) => {
	console.group(
		`${DateTime.now().toLocaleString(
			DateTime.TIME_24_WITH_SHORT_OFFSET
		)} Webhook handler started`
	)
	console.dir(events)
	await Promise.all(
		events.map(async (event: WebhookEvent) => {
			console.dir('Event', event)
			webhookLogger(event)
			switch (true) {
				case deletedAttachment(event):
					const result = await detachIssue(event)
					return result
					break
				case taskAssigned(event):
					console.log('handle task assignment')
					console.groupEnd()
					break
				case statusChanged(event):
					console.log('handle column switch')
					console.groupEnd()
					break
				case tagChanged(event):
					console.log('handle tagging/untagging')
					console.groupEnd()
					break
				default:
					console.log('event not handled')
					console.groupEnd()
					return
			}
		})
	)
}

type CheckCase = (event: WebhookEvent) => boolean

// Generated by https://quicktype.io

export interface WebhookEvent {
	action: 'added' | 'changed' | 'removed' | 'deleted'
	change: Change
	created_at: string
	parent: Parent | null
	resource: Resource
	type: string
	user: Parent
}

type Change = {
	action: string
	field: string
} & ChangeType<'added_value' | 'new_value' | 'removed_value'>

interface Value {
	gid: string
	resource_type: string
}
interface Resource {
	gid: string
	resource_type: string
	resouce_subtype?: string
}

interface Parent {
	gid: string
	resource_type: string
	name?: string
}

type ChangeType<Type> = {
	[Property in keyof Type]: Value
}
